name: Tailwind Traders CI/CD

on: 
  push:
    paths:
    - Source/Tailwind.Traders.Web/**
    branches:
      - master    

jobs:
  buildpush:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: npm install and build
      working-directory: Source\Tailwind.Traders.Web\ClientApp
      shell: pwsh
      run: |
        npm install
        npm run build
    - name: dotnet build
      working-directory: Source\Tailwind.Traders.Web
      shell: pwsh
      run: |
        dotnet restore
        dotnet publish -o out
        xcopy ClientApp\build\*.* out\ClientApp\build
        
    # deploy web app using publish profile credentials
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: ${{ secrets.WEBSITE_NAME }}
        publish-profile: ${{ secrets.WEBSITE_PUBLISH_PROFILE }}
        working-directory: Source\Tailwind.Traders.Web\out
    